## Deliverable 3. Create a Travel Itinerary Map.

In [1]:
# Dependencies and Setup
import pandas as pd
import requests
import gmaps

# Import API key
from config import g_key

# Configure gmaps
gmaps.configure(api_key=g_key)

In [2]:
# 1. Read the WeatherPy_vacation.csv into a DataFrame.
vacation_df = pd.read_csv("cities_d1.csv")
vacation_df.head()

City_ID     City Country      Lat       Lng  Max Temp  Humidity  \
0        0   Linxia      CN  35.6003  103.2064    267.27        82   
1        1  Samarai      PG -10.6167  150.6667    300.91        74   
2        2  Rikitea      PF -23.1203 -134.9692    299.90        69   
3        3    Vaini      TO -21.2000 -175.2000    299.15        89   
4        4  Ushuaia      AR -54.8000  -68.3000    280.15        61   

   Cloudiness  Wind Speed  
0          94        0.42  
1         100        2.92  
2          33        5.30  
3          75        3.09  
4          75       11.83

In [3]:
# 2. Using the template add city name, the country code, the weather description and maximum temperature for the city.
info_box_template = str(vacation_df[["City","Country","Max Temp"]])

# 3a. Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in vacation_df.iterrows()]

# 3b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = vacation_df[["Lat", "Lng"]]


In [4]:
# 4a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(30.0, 31.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 4b. Display the figure
fig

Figure(layout=FigureLayout(height='420px'))

In [5]:
# From the map above pick 4 cities and create a vacation itinerary route to travel between the four cities. 
# 5. Create DataFrames for each city by filtering the 'vacation_df' using the loc method. 
# Hint: The starting and ending city should be the same city.

vacation_start = vacation_df.loc[(vacation_df["City"] == "Ploemeur")]
vacation_end = vacation_df.loc[(vacation_df["City"] == "Ploemeur")]
vacation_stop1 = vacation_df.loc[(vacation_df["City"] == "Sainte-Maxime")]
vacation_stop2 = vacation_df.loc[(vacation_df["City"] == "Chaumont")] 
vacation_stop3 = vacation_df.loc[(vacation_df["City"] == "Kaprijke")]

In [6]:
vacation_start

City_ID      City Country      Lat     Lng  Max Temp  Humidity  \
369      369  Ploemeur      FR  47.7333 -3.4333    284.15       100   

     Cloudiness  Wind Speed  
369          90        5.14

In [7]:
# 6. Get the latitude-longitude pairs as tuples from each city DataFrame using the to_numpy function and list indexing.
start = vacation_start[["Lat", "Lng"]].to_numpy()
end = vacation_end[["Lat", "Lng"]].to_numpy()
stop1 = vacation_stop1[["Lat", "Lng"]].to_numpy()
stop2 = vacation_stop2[["Lat", "Lng"]].to_numpy()
stop3 = vacation_stop3[["Lat", "Lng"]].to_numpy()

In [8]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
import gmaps
import gmaps.datasets
gmaps.configure(api_key=g_key)


#fig = gmaps.figure()
#trip = gmaps.directions_layer(start, stop1, stop2, stop3, end)
#fig.add_layer(trip)
#fig

#doing it the module's way runs error
fig = gmaps.figure()
trip_directions= gmaps.directions_layer(
        start, end, waypoints=[stop1, stop2, stop3],
        travel_mode='BICYCLING')
fig.add_layer(trip_directions)
fig


TraitError: [[47.7333 -3.4333]] is not a valid location. Locations must have length 2.

In [9]:
#printing instead to get exact values
print(start)
print(end)
print(stop1)
print(stop2)
print(stop3)

[[47.7333 -3.4333]]
[[47.7333 -3.4333]]
[[43.3     6.6333]]
[[48.1167  5.1333]]
[[51.208   3.6273]]


In [10]:
# 7. Create a direction layer map using the start and end latitude-longitude pairs,
# and stop1, stop2, and stop3 as the waypoints. The travel_mode should be "DRIVING", "BICYCLING", or "WALKING".
import gmaps
import gmaps.datasets
gmaps.configure(api_key=g_key)

start = (47.7333, -3.4333)
end = (47.7333, -3.4333)
stop1 = (43.3, 6.6333)
stop2 = (48.1167, 5.1333)
stop3 = (51.208, 3.6273)


fig = gmaps.figure()
trip_directions= gmaps.directions_layer(
        start, end, waypoints=[stop1, stop2, stop3],
        travel_mode='DRIVING')
fig.add_layer(trip_directions)
fig

Figure(layout=FigureLayout(height='420px'))

In [11]:
# 8. To create a marker layer map between the four cities.
#  Combine the four city DataFrames into one DataFrame using the concat() function.
itinerary_df = pd.concat([vacation_start, vacation_end, vacation_stop1, vacation_stop2, vacation_stop3],ignore_index=True)
itinerary_df

City_ID           City Country      Lat     Lng  Max Temp  Humidity  \
0      369       Ploemeur      FR  47.7333 -3.4333    284.15       100   
1      369       Ploemeur      FR  47.7333 -3.4333    284.15       100   
2      560  Sainte-Maxime      FR  43.3000  6.6333    280.93        45   
3      381       Chaumont      FR  48.1167  5.1333    273.15        90   
4      482       Kaprijke      BE  51.2080  3.6273    276.48        77   

   Cloudiness  Wind Speed  
0          90        5.14  
1          90        5.14  
2         100        3.19  
3         100        2.70  
4         100        1.79

In [12]:
# 9 Using the template add city name, the country code, the weather description and maximum temperature for the city. 
info_box_template = str(itinerary_df[["City","Country","Max Temp"]])

# 10a Get the data from each row and add it to the formatting template and store the data in a list.
hotel_info = [info_box_template.format(**row) for index, row in itinerary_df.iterrows()]

# 10b. Get the latitude and longitude from each row and store in a new DataFrame.
locations = itinerary_df[["Lat", "Lng"]]

In [13]:
# 11a. Add a marker layer for each city to the map.
# 11a. Add a marker layer for each city to the map. 
fig = gmaps.figure(center=(15.0, -15.0), zoom_level=1.5)
marker_layer = gmaps.marker_layer(locations, info_box_content=hotel_info)
fig.add_layer(marker_layer)
# 11b. Display the figure
fig 

Figure(layout=FigureLayout(height='420px'))